### PR TITLE
feature/Add-configuration-file

### PR DESCRIPTION
**Pull request by danielway**
Introduces two configuration files:

**app.config**

This one is checked-in to source control, so we all have the same copy. It drives our Globus credentials and narrative ID.

**env.config**

This one is _not_ checked-in to source control, so _**we all have our own copy**_. This controls the driver path and type. It will default to a Chrome driver at `./drivers/chromedriver`.

Here are what the files look like, including my personal `env.config`:

image

### CODE REVIEW

**Review by jakedv24 — APPROVED** [review]
Yessir perfect. I like this much more than we all checking in a ton of changing local drivers.

**Comment by danielway** [comment]
Rebased on `master` and accommodated the style rules. I'm not a fan of having to break variable declarations into multiple lines (from a format like `String a, b, c;`), so maybe that's a rule we revisit.

How do you have the IntelliJ integration configured? I had to build from Maven to see the errors, and IntelliJ couldn't parse the messages/line-numbers from its output (for some reason).

**Comment by jakedv24** [comment]
> Rebased on `master` and accommodated the style rules. I'm not a fan of having to break variable declarations into multiple lines (from a format like `String a, b, c;`), so maybe that's a rule we revisit if anyone else finds it obnoxious.
> 
> How do you have the IntelliJ integration configured? I had to build from Maven to see the errors, and IntelliJ couldn't parse the messages/line-numbers from its output (for some reason).

I currently don't have any IntelliJ configuration setup beyond running the check on Maven-Validate. Does it not run  the check on play? I also saw the messages not showing in Intellij console. For me I would run `mvn checkstyle:checkstyle` which will generate a report in the targets folder

**Comment by jakedv24** [comment]
> Rebased on `master` and accommodated the style rules. I'm not a fan of having to break variable declarations into multiple lines (from a format like `String a, b, c;`), so maybe that's a rule we revisit if anyone else finds it obnoxious.
> 

Just as a note for everyone, the config file is based from the default Sun config file with some removals of checks for stuff and changing line length from 60 to 120.

**Review by jakedv24 — APPROVED** [review]
I like the separation between local configs and the business logic.

**Comment by danielway** [comment]
Re: running the checks, it doesn't run them when I debug the app but I'll just remember to run those pre-PR. Thanks for the notes.

**Pull request merged**
