### PR TITLE
File Reading. 

### PR DESCRIPTION
**Pull request by DaultonLeach**
Combining the functinonality tonight

### CODE REVIEW

**Comment by danielway** [comment]
The diffs are difficulty to follow. Could you please include a description and/or some screenshots of the change?

**Comment by DaultonLeach** [comment]
> The diffs are difficult to follow. Could you please include a description and/or some screenshots of the change?

Sure. Mainly I changed 2 things. For starters, I took most of the button activations and moved them out of the GUIForm class. This is a temporary home until we decide how exactly we are refactoring/abstracting them. Just wanted to get the logic out of that class and into a seperate call. 
Secondly, I added file reading functionality. The user can now select a file from their system and we will read in (only 1 currently) job from that file and send it to the Runner

**Review by danielway — APPROVED** [review]
Thanks for the explanation Daulton, this looks good to me!

**Comment by DaultonLeach** [comment]
merging and closing

**Pull request merged**
