### PR TITLE
feature/Abstract-input-types

### PR DESCRIPTION
**Pull request by danielway**
_Please do not merge this pull-request for me._ I am going to leave it out so everybody has opportunity to review and ask questions about these changes.

**Background**

Fundamentally, KBase allows applications (what we think of as cards like the FBA card) to specify parameters. These parameters and their GUI code are not re-written for every application, but rather the author of each application specifies parameters in a JSON format. Parameters each have a _type_, such as checkbox, text, or list. Within the FBA application and across other applications in KBase, parameters must each have a "type" from the predefined list offered by KBase. This type drives the GUI options/behavior we see in KBase, so the GUI behavior and DOM selectors will be standard between fields that share the same type.

The v2 FBA application changed some parameters' types, such as Media Supplement from a simple list of strings to a searchable multi-option selection. Currently, we have duplicated (and in some cases implemented differently) automation code for each input type. For example, multiple inputs have searchable option selections, so we've duplicated the code to remove previous selections, search for new selections, and add them. This means we need to revisit and reimplement those parameters whose types have changed.

**Proposed Solution**

This PR refactors our automation code so that it is organized by type rather than individual parameters. This means instead of calling `programReactionToMaximize`, we call `KBaseHelper.setSearchableOptionList`. Rather than duplicating the code to interact with each input type, we have common code for each input type and simply specify the unique variables for each parameter.

This is beneficial for a few reasons:

1. Our code is easier to maintain when changes like this happen, since we don't have duplicated code
2. We can extend our code to applications other than FBAs in the future without duplicating large amounts of automation code
3. Our code is more understandable as low-level automation is separated from any parameter-specific behaviors

Please let me know your thoughts or if you have any questions.

### CODE REVIEW

**Review by PukTheGreat — APPROVED** [review]
Looks good, nice and clean

**Comment by danielway** [comment]
I completely resent this forced style checker. In my opinion, this code would be better if I let it go 2 characters longer than the rule instead of breaking the line.

**Comment by DaultonLeach** [comment]
Very well done. Looks good to me. This will let the next team extend to new test types more easily correct?

**Comment by danielway** [comment]
@DaultonLeach I think so. If new parameters of existing types come along, it will be trivial to add them, and if we need to implement entirely new types in the future they can simply be added to the helper.

**Review by jakedv24 — APPROVED** [review]
Looks a hell of a lot cleaner to me. :+1: does this abstraction make the choice more testable?

**Review by jakedv24 — APPROVED** [review]

**Comment by danielway** [comment]
> Looks a hell of a lot cleaner to me. 👍 does this abstraction make the code more testable?

Yes, I think it does. We can test the KBase automation functions in `KBaseHelper` separately from our app-specific programmers like the `FBASeleniumInputProgrammer`. With those, we can simply assert that they're calling the helper with the correct parameters, rather than needing to ensure every parameter/application is correctly issuing Selenium commands.

**Review by clmeyer42 — APPROVED** [review]

**Pull request merged**
