### PR TITLE
feature/Implement-basic-auth-flow

### PR DESCRIPTION
**Pull request by danielway**
This implements a basic Globus authentication flow. It currently uses the Firefox webdriver, but I include instructions to setup Chrome. It will attempt to load a narrative, step through the Globus login flow, and end-up on the narrative. This is not API-authenticating, but rather interacting with the forms the same way a user would.

This also presents a possible initial project setup, using Maven for dependency management and JUnit for testing. We can certainly go another direction with this if we prefer.

Next steps will be to copy the narrative we've been provided with so we can edit it, and start to write instructions for Selenium to identify and fill form fields. There should be plenty of examples in this code of how to interact with the DOM in a variety of ways:
- Locating elements by ID, class, CSS selector, or tag name
- Adjusting the driver's scope (between the high-level window or an iFrame within the window)
- Inputting content into a form field
- Clicking buttons

This also demonstrates a couple of approaches to handling asynchronous interaction between loads.

[This file contains most of the interesting work](https://github.com/jakedv24/senior-design-sdmay21-26/blob/7a83db54839a5b2056c92fe49a802a0b127b5912/src/main/java/edu/iastate/ece/sd/sdmay2126/App.java) (if you want to avoid the project files).

**Edit: [Here's the demonstration video](https://drive.google.com/file/d/1bxIteh-QYNss7fNzU9aC2s2dN_CrBFKZ/view?usp=sharing).**

### CODE REVIEW

**Review by jakedv24 — APPROVED** [review]
LGTM :+1:

**Comment by danielway** [comment]
Updated the pull-request to include the demonstration video of the authentication flow.

I see the CI check is failing. I'll take a look if I have a chance today.

**Review by DaultonLeach — APPROVED** [review]
Looks like a great first step, Good work Daniel.

**Comment by danielway** [comment]
Testing whether GitHub will share this in our Slack channel.

**Review by clmeyer42 — APPROVED** [review]

**Pull request merged**
